### PR TITLE
Chapter 2 Rewrites and Edits

### PR DESCRIPTION
**Pull request by shiffman**
So far I've edited up until section 2.5

### CODE REVIEW

**Comment by shiffman** [comment]
Making a note here that I am rewriting Chapter 2 to not introduce arrays until the many attractors examples. The initial examples of a "bouncing ball" examples are changing a bit to be more clear based on my in-class teaching experience.

**Comment by shiffman** [comment]
This is complete! @joeyklee I like the idea as with #62 leaving these to you to merge as a second pair of eyes to make sure I haven't done something crazy? It's also a good guide for you to see way I am updating to match consistency in later chapters, etc.

**Comment by joeyklee** [comment]
@shiffman - Should I go ahead and make these updates from my feedback on chapters 2, 3, and 4 or do you want to go through those copy edits/feedback?

**Comment by shiffman** [comment]
Hey! Sorry I lost this thread in my getting too swept up with other projects this semester, let's discuss in person later this week!

**Comment by shiffman** [comment]
I'm returning to this and rendering new chapter PDFs for the [spring 2020 course](https://github.com/nature-of-code/noc-syllabus-S20) each week, yay! I think we had a process before where we were still reviewing these, but for expediency I am going to merge and complete future edits in a new branch.

**Comment by joeyklee** [comment]
@shiffman - sounds good. My notes are here in the above thread.

**Pull request merged**
