### PR TITLE
Chapter 4 Edits

### PR DESCRIPTION
**Pull request by shiffman**
Just a start so far. . .

### CODE REVIEW

**Comment by shiffman** [comment]
Noting a couple open questions as I pause at section 4.5.

1. Once I add `origin` this code becomes a little awkward, might reconsider.

```javascript
  addParticle() {
    this.particles.push(new Particle(this.origin.x, this.origin.y));
  }
```

2. `applyForce()` gravity should maybe end up in the `ParticleSystem` class, but maybe I just address this later in the chapter.

Code updates: https://github.com/nature-of-code/noc-examples-p5.js/pull/93

**Comment by shiffman** [comment]
@joeyklee also if you look at my changes so far I decided to go with `splice()` over `filter()` but keeping a reference to `filter()`. I should also probably explain that there is a `for in` loop and a `forEach()` higher-order function somewhere.

**Comment by shiffman** [comment]
Just under 7 months later I have returned to editing this chapter! Merging in the final changes and noting small things remaining in separate issues.

**Comment by joeyklee** [comment]
Hooray! Excellent!

**Pull request merged**
